version: '3.8'

services:
  spring-redis:
    image: redis
    container_name: spring-redis
    ports:
      - "6379:6379"
    networks:
      - spring-redis-network
    volumes:
      - redis-data:/data

  spring-redis-cli:
    image: redis
    entrypoint: ["redis-cli", "-h", "spring-redis"]
    networks:
      - spring-redis-network
    stdin_open: true
    tty: true
    depends_on:
      - spring-redis

volumes:
  redis-data:
    name: redis-data

networks:
  spring-redis-network:
    name: spring-redis-network
